from Classes2 import Circle, Cylinder

drum1 = Cylinder(5.0, 3.0, "blue")
print("Data Cylinder Before Setting Variable")
print("Radius     :", drum1.getRadius())
print("Color      :", drum1.getColor())
print("Height     :", drum1.getHeight())
print("Base Area  :", drum1.getArea())
print("Volume     :", drum1.getVolume())

drum1.setHeight(3.0)
print()
print("Data Cylinder After Setting Height to 3.0")
print("Radius     :", drum1.getRadius())
print("Color      :", drum1.getColor())
print("Height     :", drum1.getHeight())
print("Base Area  :", drum1.getArea())
print("Volume     :", drum1.getVolume())

drum1.setRadius(2.0)
print()
print("Data Cylinder After Setting Height to 3.0 and Radius to 2.0")
print("Radius     :", drum1.getRadius())
print("Color      :", drum1.getColor())
print("Height     :", drum1.getHeight())
print("Base Area  :", drum1.getArea())
print("Volume     :", drum1.getVolume())

drum1.setColor("green")
print()
print("Data Cylinder After Setting Height to 3.0 and Radius to 2.0 then set color to green")
print("Radius     :", drum1.getRadius())
print("Color      :", drum1.getColor())
print("Height     :", drum1.getHeight())
print("Base Area  :", drum1.getArea())
print("Volume     :", drum1.getVolume())